// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Y3j_pCOuztULXiXN-veUzNUNPRcdqKw',
    appId: '1:72829162068:web:9e00472e6d67b8bb5a53c1',
    messagingSenderId: '72829162068',
    projectId: 'vision2-c6fd0',
    authDomain: 'vision2-c6fd0.firebaseapp.com',
    storageBucket: 'vision2-c6fd0.appspot.com',
    measurementId: 'G-STN66MRCFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ4DApw1YV49WN0zpDUrmRhz-kv7LPnoM',
    appId: '1:72829162068:android:30b4676f1e0e963e5a53c1',
    messagingSenderId: '72829162068',
    projectId: 'vision2-c6fd0',
    storageBucket: 'vision2-c6fd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4RixbAQRWXVROvZS70VP37DCmsX_42x0',
    appId: '1:72829162068:ios:3ae69a661d64bd595a53c1',
    messagingSenderId: '72829162068',
    projectId: 'vision2-c6fd0',
    storageBucket: 'vision2-c6fd0.appspot.com',
    iosBundleId: 'com.example.flutterApplicationVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4RixbAQRWXVROvZS70VP37DCmsX_42x0',
    appId: '1:72829162068:ios:3ae69a661d64bd595a53c1',
    messagingSenderId: '72829162068',
    projectId: 'vision2-c6fd0',
    storageBucket: 'vision2-c6fd0.appspot.com',
    iosBundleId: 'com.example.flutterApplicationVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Y3j_pCOuztULXiXN-veUzNUNPRcdqKw',
    appId: '1:72829162068:web:43f0da0e31ff59465a53c1',
    messagingSenderId: '72829162068',
    projectId: 'vision2-c6fd0',
    authDomain: 'vision2-c6fd0.firebaseapp.com',
    storageBucket: 'vision2-c6fd0.appspot.com',
    measurementId: 'G-61KEMRM318',
  );
}
